/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ic7cc.ovchinnikov.compiler;

import ic7cc.ovchinnikov.compiler.lexer.Lexer;
import ic7cc.ovchinnikov.compiler.parser.Parser;

import java.io.FileReader;

public class App {

    public static void main(String[] args) throws Exception {
        Parser parser = new Parser(new Lexer(new FileReader("lua/function.lua")));
        parser.parse();
    }
}
