
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 30 01:01:12 MSK 2020
//----------------------------------------------------

package ic7cc.ovchinnikov.compiler.parser;

/** CUP generated interface containing symbol constants. */
public interface Token {
  /* terminals */
  public static final int POW = 31;
  public static final int FUNCTION = 7;
  public static final int LBRACKET = 50;
  public static final int ASSIGNMENT = 2;
  public static final int CONCAT = 32;
  public static final int FDIV = 29;
  public static final int LPAREN = 48;
  public static final int REPEAT = 13;
  public static final int LESS = 36;
  public static final int FOR = 11;
  public static final int BXOR = 45;
  public static final int RPAREN = 49;
  public static final int SEMICOLON = 54;
  public static final int NOT = 46;
  public static final int AND = 39;
  public static final int ELSEIF = 18;
  public static final int NIL = 21;
  public static final int OR = 40;
  public static final int IN = 12;
  public static final int COMMA = 55;
  public static final int BAND = 41;
  public static final int DIV = 28;
  public static final int UNTIL = 14;
  public static final int BLEFT = 44;
  public static final int MOREEQ = 38;
  public static final int LESSEQ = 34;
  public static final int IF = 15;
  public static final int ID = 58;
  public static final int DOT = 3;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int RBRACKET = 51;
  public static final int EQUAL = 33;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int ADD = 25;
  public static final int MOD = 30;
  public static final int BREAK = 20;
  public static final int PARAMS = 24;
  public static final int COLONCOLON = 5;
  public static final int COLON = 4;
  public static final int LBRACE = 52;
  public static final int BOR = 42;
  public static final int ELSE = 17;
  public static final int LITERAL_STRING = 57;
  public static final int WHILE = 10;
  public static final int NUMERAL = 56;
  public static final int RBRACE = 53;
  public static final int THEN = 16;
  public static final int END = 8;
  public static final int LOCAL = 6;
  public static final int FALSE = 22;
  public static final int SUB = 27;
  public static final int BRIGHT = 43;
  public static final int LENGTH = 47;
  public static final int MORE = 37;
  public static final int DO = 9;
  public static final int NOTEQ = 35;
}

