
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 29 21:32:25 MSK 2020
//----------------------------------------------------

package ic7cc.ovchinnikov.compiler.parser;

/** CUP generated interface containing symbol constants. */
public interface Token {
  /* terminals */
  public static final int POW = 30;
  public static final int FUNCTION = 7;
  public static final int LBRACKET = 48;
  public static final int ASSIGNMENT = 2;
  public static final int CONCAT = 31;
  public static final int LPAREN = 46;
  public static final int REPEAT = 13;
  public static final int LESS = 35;
  public static final int FOR = 11;
  public static final int RPAREN = 47;
  public static final int SEMICOLON = 52;
  public static final int NOT = 44;
  public static final int AND = 38;
  public static final int ELSEIF = 18;
  public static final int NIL = 21;
  public static final int OR = 39;
  public static final int IN = 12;
  public static final int COMMA = 53;
  public static final int BAND = 40;
  public static final int DIV = 28;
  public static final int UNTIL = 14;
  public static final int BLEFT = 43;
  public static final int MOREEQ = 37;
  public static final int LESSEQ = 33;
  public static final int IF = 15;
  public static final int ID = 56;
  public static final int DOT = 3;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int RBRACKET = 49;
  public static final int EQUAL = 32;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int ADD = 25;
  public static final int MOD = 29;
  public static final int BREAK = 20;
  public static final int PARAMS = 24;
  public static final int COLONCOLON = 5;
  public static final int COLON = 4;
  public static final int LBRACE = 50;
  public static final int BOR = 41;
  public static final int ELSE = 17;
  public static final int GOTO = 57;
  public static final int LITERAL_STRING = 55;
  public static final int WHILE = 10;
  public static final int NUMERAL = 54;
  public static final int RBRACE = 51;
  public static final int THEN = 16;
  public static final int END = 8;
  public static final int LOCAL = 6;
  public static final int FALSE = 22;
  public static final int SUB = 27;
  public static final int BRIGHT = 42;
  public static final int LENGTH = 45;
  public static final int MORE = 36;
  public static final int DO = 9;
  public static final int NOTEQ = 34;
}

